version: '3.8'

services:
  db-postgres:
    image: postgres:16.3-alpine3.18
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/datasource/comic:/var/lib/postgresql/data
    networks:
      - ${GLOBAL_NETWORK:-db-postgres}