CREATE TABLE IF NOT EXISTS categories (
  id BIGINT NOT NULL,
   name VARCHAR(255) NOT NULL,
   created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
   updated_at TIMESTAMP(6) WITH TIME ZONE,
   deleted_at TIMESTAMP(6) WITH TIME ZONE,
   CONSTRAINT pk_categories PRIMARY KEY (id)
);