version: '3.8'

services:
    comic-service:
        image: org.zender.comic.comic-service:${APPLICATION_VERSION}
        ports:
            - ${COMIC_SERVICE_PORT}:9201
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://db-postgres:${POSTGRES_PORT}/${POSTGRES_DB}?currentSchema=comic-service
            SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
            SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
        networks:
            - ${GLOBAL_NETWORK:-comic-service}
