version: '3.8'

services:
  db-postgres:
    image: postgres:${POSTGRES_VERSION}
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./volumes/datasource:/var/lib/postgresql/data
    networks:
      - ${GLOBAL_NETWORK:-db-postgres}