spring:
  sql:
    init:
      platform: none
  jpa:
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/comic?currentSchema=comic-service
    username: postgres
    password: postgres

  flyway:
    schemas:
      - comic-service
    baselineOnMigrate: true
    locations: classpath:db/migration
