name: Build Development Environment
on:
  push:
    branches:
      - development
  pull_request:
    types:
      - closed
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
      - name: Test Comic Service
        run: |
          mvn clean
          mvn verify -pl comic-service/comic-domain -am
          mvn verify -pl comic-service/comic-application -am
          mvn verify -pl comic-service/comic-infrastructure -am
          mvn verify -pl comic-service/comic-presentation -am
  build:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build image
        run: |
          mvn clean package -DskipTests -Ddocker.skip=false
