name: pull request check
on:
  pull_request:
    branches:
      - master
      - development
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Test Comic Service
        run: |
          mvn clean verify -pl \
            comic-service/comic-domain, \
            comic-service/comic-application, \
            comic-service/comic-infrastructure, \
            comic-service/comic-presentation \
          -am