name: pull request check
on:
  pull_request:
    branches:
      - master
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean verify
      - name: Test Report
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: SpringBoot Report               # Name of the folder
          path: target/site/serenity/           # Path to test results