server:
  port: 9201

spring:
  application:
    name: comic-service
  output:
    ansi:
      enabled: always
  config:
    import:
      - 'classpath:application-infra.yml'
logging:
  level:
    root: info
    org.springframework: info
